### ISSUE TITLE
Infinite Loading Screen When API is not Available

### ISSUE THREAD

**Issue by kondanta** [Egomination/quela#1]
Since I'm using the builder, there's a line inside of the builder like `return CircularProgress` if data's not available. So we need to handle it properly and show/let the user know there's a connectivity issue going on.

**Comment by kondanta** [comment]
So I was looking for a solution and I realized `.timeout` function in _bloc_ files has actually `.then` function which returns to _FutureOr_. I will try to use this functionality to resend query after we reach the timeout. It's just a one possible solution for the problem but like I said, its _a possbility_ not a precise solution.

edit: Another solution would be putting a refresh button on the app bar.

**Comment by sasalx** [comment]
Right now we are solving this issue with Bloc Pattern and Splash Image.
