### ISSUE TITLE
Dynamic Patient Dashboard Card Color Change

### ISSUE THREAD

**Issue by kondanta** [Egomination/quela#2]
For now, it depends on the custom threshold that I decided on a whim. We have to find some accurate thresholds for the data we're collecting. Also, the `CardBuilder` class is going to be changed after finding those thresholds. Because we have to change the colours of the cards depending on the given threshold whether by hand on creation or coming from the database.

**Comment by sasalx** [comment]
I will improve the API so that we will have another field for every patient value. Those fields will contain min and max values for said values. I will also make a relationship with patient data so that you can access those data with one query.

**Comment by kondanta** [comment]
Alright, I am closing this issue since its fixed with the latest commit on develop.
