### ISSUE TITLE
Padding looks weird on different phones

### ISSUE THREAD

**Issue by kondanta** [Egomination/quela#3]
I realized that the custom padding looks different depending on the screen size. So we've to utilize media query type of padding/sizing to make them compatible on all Android devices.

**Comment by sasalx** [comment]
Which parts of the UI affected with this?

**Comment by kondanta** [comment]
Alarm's white dividers.

**Comment by kondanta** [comment]
Fixed in: https://github.com/Egomination/quela/commit/4317ff763d4a0e12ef3ca9bccbde5edf9326237c
